[package]
name = "stdf2text"
version = "0.1.0"
edition = "2021"
linker = "rust-lld"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
stdf_reader = { version = "0.1", path = "../stdf-reader/" }
