name: Windows Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: false
        default: 'master'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Build
      run: |
        rustc --version
        cargo build --verbose -r --target=x86_64-pc-windows-msvc
    - name: Run tests
      run: cargo test --verbose -r --target=x86_64-pc-windows-msvc
