name: Linux Build and Test

on:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'info'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Install Dependencies # This would actually build your project, using zip for an example artifact
      run: |
        sudo apt-get install -y musl musl-tools musl-dev
        rustup target add x86_64-unknown-linux-musl
    - name: Rust Version # This would actually build your project, using zip for an example artifact
      run: rustc --version
    - name: Build Project # This would actually build your project, using zip for an example artifact
      run: cargo build --verbose -r --target=x86_64-unknown-linux-musl
    - name: Test Project # This would actually build your project, using zip for an example artifact
      run: cargo test --verbose -r --target=x86_64-unknown-linux-musl
