name: Linux Build and Test

on:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'info'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - uses: stevenleadbeater/rust-musl-builder@master
      with:
        args: /bin/bash -c "rustc --version; cargo build --verbose -r --target=x86_64-unknown-linux-musl"
    - uses: stevenleadbeater/rust-musl-builder@master
      with:
        args: /bin/bash -c "rustc --version; cargo test --verbose -r --target=x86_64-unknown-linux-musl"
    #- name: Build
    #  uses: stevenleadbeater/rust-musl-builder@master
    #  run: |
    #    rustc --version
    #    cargo build --verbose -r --target=x86_64-unknown-linux-musl
    #- name: Run tests
    #  run: cargo test --verbose -r --target=x86_64-unknown-linux-musl
