on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

name: Linux Upload MUSL Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Build Cache
        uses: actions/cache@v3
        with:
          path: |
            ./target/

      - name: Install Dependencies # This would actually build your project, using zip for an example artifact
        run: |
          sudo apt-get install -y musl musl-tools musl-dev
          rustup target add x86_64-unknown-linux-musl

      - name: Rust Version # This would actually build your project, using zip for an example artifact
        run: rustc --version

      - name: Build Project # This would actually build your project, using zip for an example artifact
        run: cargo build --verbose -r --target=x86_64-unknown-linux-musl

      - name: Tarball Assets # This would actually build your project, using zip for an example artifact
        run: tar -czf linux_musl.tgz -C target/x86_64-unknown-linux-musl/release/ libstdf_reader.a libstdf_reader.rlib stdf2csv stdf2text stdf2ufile stdf2ui
      
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./linux_musl.tgz